version: '3.7'
services:

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/web/site/src:/app/src
      - ./services/web/site/gatsby-browser.js:/app/gatsby-browser.js
      - ./services/web/site/gatsby-config.js:/app/gatsby-config.js
      - ./services/web/site/gatsby-node.js:/app/gatsby-node.js
      - ./services/web/site/gatsby-ssr.js:/app/gatsby-ssr.js

networks:
  frontend: